sudo: required
services:
  - docker

before_install:
  - docker build -t bretonne/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev

script:
  - docker run bretonne/react-test npm test -- --coverage

after_success:
  - docker build -t bretonne/multi-client ./client
  - docker build -t bretonne/multi-nginx ./nginx
  - docker build -t bretonne/multi-server ./server
  - docker build -t bretonne/multi-worker ./worker
# login to docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
# take those into dockerhub
- docker push bretonne/multi-client
- docker push bretonne/multi-nginx
- docker push bretonne/multi-server
- docker push bretonne/multi-worker